groups:
- name: build
  jobs:
  - testflight
  - rc
  - shipit
- name: version
  jobs:
  - patch
  - minor
  - major

jobs:
- name: testflight
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: spruce
        resource: git-spruce
        trigger: true
    - task: run_tests
      config:
        platform: linux
        image: {{docker-hub-task-image}}
        inputs:
        - name: spruce
          path: .
        run:
          path: ./ci/scripts/run_tests.sh
          args: []

- name: rc
  public: true
  plan:
  - aggregate:
    - get: spruce
      resource: git-spruce
      passed: [testflight]
      trigger: true
    - get: version
      trigger: false
      params: {pre: rc}
    - get: homebrew-repo
      resource: git-homebrew-cf
      trigger: false
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: patch}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: major}
  - put: version
    params: {file: version/number}

- name: shipit
  public: true
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [rc]
      params: {bump: final}
    - get: spruce
      resource: git-spruce
      passed: [rc]
  - task: create-final-release
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - name: spruce
      - name: version
      run:
        path: ./spruce/ci/scripts/shipit.sh
        args: []
      params:
        RELEASE:      Spruce Release
        VERSION_FROM: ../version/number
  - put: git-spruce
    params:
      repository: create-final-release/spruce
      rebase: true
  - task: update-homebrew
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - name: homebrew-repo
      - name: spruce
      - name: create-final-release
      - name: version
      run:
        path: ./spruce/ci/scripts/update-homebrew.sh
        args: spruce.rb
      params:
        VERSION_FROM: ../version/number
  - put: homebrew-repo
    params:
      repository: update-homebrew/homebrew-repo
      rebase: true
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: github-final-release
      params:
        name: create-final-release/spruce/releases/name
        tag: create-final-release/spruce/releases/tag
        body: create-final-release/spruce/releases/notes.md
        globs:
        - create-final-release/spruce/releases/spruce-*

resources:
- name: version
  type: semver
  source:
    key: current-version
    bucket: {{pipeline-aws-bucket}}
    access_key_id: {{pipeline-aws-access-key-id}}
    secret_access_key: {{pipeline-aws-secret-access-key}}
    initial_version: 0.2.0

- name: git-spruce
  type: git
  source:
    uri: git@github.com:geofffranks/spruce.git
    branch: master
    private_key: {{github-private-key}}

- name: git-homebrew-cf
  type: git
  source:
    uri: git@github.com/starkandwayne/homebrew-cf.git
    branch: master
    private_key: {{github-private-key}}

- name: github-final-release
  type: github-release
  source:
    user: geofffranks
    repository: spruce
    access_token: {{github-access-token}}
